### ISSUE TITLE
Add IncreaseKey support 

### ISSUE THREAD

**Issue by pushinginertia** [starwander/GoFibonacciHeap#2]
`DecreaseKey` updates the key for a given node and if it no longer satisfies the identity `parentNode.key <= node.key <= allChildrenNodes.key`, the node (with its children) is removed from the tree and becomes a new root tree. `node.key <= allChildrenNodes.key` would continue to hold because `node.key` is only decrementing.

Propose adding an `IncreaseKey` method that checks the node's children and for any child node with a key no longer satisfying the `node.key <= childNode.key` identity, the child node is removed and becomes a new root tree. This should provide the same O(1) runtime as `DecreaseKey`.

Something like:

```go
func (heap *FibHeap) increaseKey(n *node, value Value, key float64) error {
       if key < n.key {
               return errors.New("New key is less than current key")
       }

       n.key = key
       n.value = value

       // Make any child with a key less than the current node's new key a root node.
       for child := n.children.Front(); child != nil; child = child.Next() {
               childNode := child.Value.(*node)
               if childNode.key < n.key {
                       // Make root node
                       heap.cut(childNode)
                       heap.cascadingCut(n)
               }
       }

       // Identify new min if this was set to be the heap's min.
       if heap.min == n {
               heap.resetMin()
       }

       return nil
}
```

**Comment by starwander** [comment]
Sorry for the late response!
I've just come back from vacation and will follow this later.

**Comment by starwander** [comment]
I've just added the support of IncreaseKey. Please update the code by 'go get -u github.com/starwander/GoFibonacciHeap' and have a try.
I'm going to close this issue. Please feel free to open a new one if this is not what you want.
